### PR TITLE
[WIP] Vulcanize upstream changes

### PR DESCRIPTION
**Pull request by Olshansk**
A port of [this PR](https://github.com/celestiaorg/smt/pull/73)

### CODE REVIEW

**Comment by i-norden** [comment]
Would appreciate it if you can retain Roy's commit history. Can have him re-open a PR here if that helps. Thanks!

**Comment by Olshansk** [comment]
@i-norden When we get to the point of merging it in: 🤝

**Comment by h5law** [comment]
> Would appreciate it if you can retain Roy's commit history. Can have him re-open a PR here if that helps. Thanks!

I am looking to merge lazy loading, so if Roy is able to open a PR in this repo to maintain his commit history I would really appreciate it. 🫠

**Comment by h5law** [comment]
@Olshansk @i-norden I will close this PR as I have opened another which retains the squashed commit history of Roy from the vulcanize repo with some modifications to make it mergeable 👍🏼

**Pull request closed without merging**
