### PR TITLE
feat: add `VersionedSMT` for historical queries

### PR DESCRIPTION
**Pull request by h5law**
### Summary generated by Reviewpad on 03 Sep 23 16:34 UTC
This pull request includes changes in multiple files:

1. The `go.mod` file was updated to change the Go version to 1.20 and add a new dependency on `golang.org/x/exp v0.0.0-20230817173708-d852ddb80c63` while removing the dependency on `github.com/google/go-cmp v0.5.8`.

2. The file `immutable.go` introduces a new type `ImmutableTree` that wraps the `SMT` struct. It also implements various methods related to the immutable behavior of the tree, such as `Update`, `Delete`, `Commit`, and `SetInitialVersion`. Additionally, it provides methods for versions and retrieval of data based on versions.

3. The file diff introduces a new interface called `VersionedSMT`, which extends the `SparseMerkleTree` interface and adds methods for versioning and managing previous versions of the tree. It also introduces the `TreeSpec` struct with a helper function for custom hashers.

4. The file `.github/workflows/test.yml` was modified to update the `TARGET_GOLANG_VERSION` environment variable and the `go` version in both jobs.

5. The file diff for `badgerKVStore.go` includes the addition of the `bytes` package import, a new method called `Clone` in the `badgerKVStore` struct, and updates to comments and existing code.

6. The file diff introduces a new file `encoding.go` with functions related to encoding and decoding of stored trees using `gob` encoding.

7. The file `Versioned.md` includes changes related to the introduction and implementation details of the `VersionedSMT` interface, the `VersionedTree` and `ImmutableTree` types, and database lifecycle details.

8. The file diff for the test file includes test functions for an immutable tree, covering various scenarios and functionalities.

9. The file diff for `utils.go` includes new functions and imports related to numeric directory handling and directory existence checks.

10. The file diff introduces a new test file `versioned_test.go` with multiple test functions for a versioned tree.

11. The file diff for `smt_utils_test.go` includes changes related to introducing hashing capabilities in the code.

12. The file `README.md` includes changes in the required Go version and additional subsections.

13. The file `encoding_test.go` contains test functions for encoding and decoding a stored tree.

14. The file `go.sum` contains changes to the dependencies.

15. The file `hasher.go` includes changes related to the `PathHasher`, `ValueHasher`, `treeHasher`, `pathHasher`, and `valueHasher` types.

Please review these changes carefully.

## Issue

Fixes N/A

## Type of change

Please mark the relevant option(s):

- [x] New feature, functionality or library
- [ ] Bug fix
- [ ] Code health or cleanup
- [ ] Major breaking change
- [ ] Documentation
- [ ] Other 

## List of changes

- Add `VersionedSMT` interface and `ImmutableTree` and `VersionedTree` implementations to wrap the SMT
- Allow for historical queries of a versioned SMT

## Testing

- [x] **Task specific tests or benchmarks**: `go test ...`
- [x] **New tests or benchmarks**: `go test ...`
- [x] **All tests**: `go test -v`

## Required Checklist

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added, or updated, [`godoc` format comments](https://go.dev/blog/godoc) on touched members (see: [tip.golang.org/doc/comment](https://tip.golang.org/doc/comment))
- [x] I have tested my changes using the available tooling

### If Applicable Checklist

- [ ] Update any relevant README(s)
- [ ] Add or update any relevant or supporting [mermaid](https://mermaid-js.github.io/mermaid/) diagrams
- [x] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by Olshansk** [comment]
@h5law Is this still a high priority?

**Comment by h5law** [comment]
@Olshansk No this is not priority anymore afaik

**Comment by Olshansk** [comment]
Let's close this out if its no longer relevant

**Comment by h5law** [comment]
This PR is no longer needed closing

**Pull request closed without merging**
